# Generated by Django 5.2.7 on 2025-12-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('cod_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nom_centro', models.CharField(choices=[('Centro de Electricidad, Electrónica y Telecomunicaciones', 'Centro de Electricidad, Electrónica y Telecomunicaciones'), ('Centro de Gestión Industrial', 'Centro de Gestión Industrial'), ('Centro de Diseño y Metrología', 'Centro de Diseño y Metrología'), ('Centro Metalmecánico', 'Centro Metalmecánico'), ('Centro Nacional de Hotelería, Turismo y Alimentos', 'Centro Nacional de Hotelería, Turismo y Alimentos'), ('Centro de Manufactura en Textil y Cuero', 'Centro de Manufactura en Textil y Cuero'), ('Centro de Materiales y Ensayos', 'Centro de Materiales y Ensayos'), ('Centro de Tecnologías para la Construcción y la Madera', 'Centro de Tecnologías para la Construcción y la Madera'), ('Centro de Servicios Financieros', 'Centro de Servicios Financieros'), ('Centro de Gestión Administrativa', 'Centro de Gestión Administrativa'), ('Centro de Gestión de Mercados, Logística y Tecnologías de la Información', 'Centro de Gestión de Mercados, Logística y Tecnologías de la Información'), ('Centro de Formación de Talento Humano en Salud', 'Centro de Formación de Talento Humano en Salud'), ('Centro para la Industria de la Comunicación Gráfica', 'Centro para la Industria de la Comunicación Gráfica'), ('Centro de Tecnologías del Transporte', 'Centro de Tecnologías del Transporte'), ('Centro de Formación en Actividad Física y Cultura', 'Centro de Formación en Actividad Física y Cultura')], max_length=100, unique=True)),
                ('ciudad_centro', models.CharField(default='Bogotá', editable=False, max_length=30)),
            ],
            options={
                'db_table': 'centro_formacion',
                'managed': False,
            },
        ),
    ]
