# Generated by Django 5.2.7 on 2025-12-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Número de Documento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionario')], max_length=20, verbose_name='Tipo de Usuario')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
