# Generated by Django 5.2.7 on 2025-12-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('cod_coordinacion', models.AutoField(primary_key=True, serialize=False)),
                ('nom_coordinacion', models.CharField(blank=True, max_length=35, null=True)),
                ('cod_centro_fk', models.ForeignKey(db_column='cod_centro_fk', on_delete=django.db.models.deletion.CASCADE, to='centros.centro', verbose_name='Centro')),
            ],
            options={
                'db_table': 'coordinacion',
            },
        ),
    ]
