# Generated by Django 5.2.7 on 2025-12-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('cod_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_reserva', models.CharField(max_length=100, verbose_name='Título de la Reserva')),
                ('tipo_reserva', models.CharField(choices=[('clase', 'Clase'), ('reunion', 'Reunión'), ('evento', 'Evento'), ('capacitacion', 'Capacitación'), ('examen', 'Examen'), ('otros', 'Otros')], max_length=100, verbose_name='Tipo de Reserva')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_ini', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('motivo', models.CharField(max_length=256, verbose_name='Motivo')),
                ('num_personas', models.IntegerField(verbose_name='Número de Personas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('recibida', 'Ambiente recibido'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('tipos_problema', models.CharField(blank=True, db_column='tipos_problema', max_length=200, null=True, verbose_name='Tipos de problema reportados')),
                ('comen_funcionario', models.CharField(blank=True, db_column='comen_funcionario', max_length=250, null=True, verbose_name='Comentario funcionario')),
                ('comen_admin', models.CharField(blank=True, db_column='comen_admin', max_length=250, null=True, verbose_name='Comentario administrador')),
                ('cod_ambiente_fk', models.ForeignKey(db_column='cod_ambiente_fk', on_delete=django.db.models.deletion.CASCADE, to='ambientes.ambiente', verbose_name='Ambiente')),
                ('cod_usuario_fk', models.ForeignKey(db_column='cod_usuario_fk', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
